services:
  nginx:
    image: nginx:1.25.3-alpine
    networks:
      - reverse-proxy
    volumes:
      - ./website:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.in-website.rule=Host(`in.rot.sgsnet.se`)"
      - "traefik.http.routers.in-website.entrypoints=websecure"
      - "traefik.http.routers.in-website-ip.rule=Host(`46.239.104.104`)"
      - "traefik.http.routers.in-website-ip.entrypoints=web"
      - "traefik.http.routers.in-website-ip.middlewares=redirect@file"

networks:
  reverse-proxy:
    external: true
